# Generated by Django 6.0.6 on 2026-06-19 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_uid', models.BigIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_uid', models.BigIntegerField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_uid', models.BigIntegerField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('user_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'folders',
            },
        ),
        migrations.CreateModel(
            name='FolderMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_uid', models.BigIntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_uid', models.BigIntegerField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_uid', models.BigIntegerField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_links', to='app.folder')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folder_links', to='app.meeting')),
            ],
            options={
                'db_table': 'folder_meetings',
                'constraints': [models.UniqueConstraint(fields=('folder', 'meeting'), name='unique_folder_meeting')],
            },
        ),
    ]
