# Generated by Codex on 2026-06-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_chatmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="type",
            field=models.CharField(
                choices=[("general", "general"), ("meeting", "meeting")],
                default="general",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="chat",
            name="meeting_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
