from __future__ import annotations

import re
from pathlib import Path

from django.core.management.base import BaseCommand, CommandError


class Command(BaseCommand):
    help = "Remove files and bindings generated by make_feature."

    def add_arguments(self, parser) -> None:
        parser.add_argument("feature_name", type=str)
        parser.add_argument(
            "--force",
            action="store_true",
            help="Delete immediately without confirmation prompt.",
        )

    def handle(self, *args, **options) -> None:
        class_name = self._normalize_class_name(options["feature_name"])
        if not class_name:
            raise CommandError("FeatureName is required")

        root = Path.cwd() / "app"
        context = {
            "class_name": class_name,
            "snake_name": self._to_snake_case(class_name),
        }
        files = self._feature_files(root, context)

        self._print_confirmation_summary(class_name, files)

        if not options["force"] and not self._confirmed():
            self.stdout.write(self.style.WARNING("Remove feature cancelled."))
            return

        deleted_files, warnings = self._delete_files(files)
        updated_model_exports = self._update_model_exports(root, class_name)
        updated_repository_bindings = self._update_repository_bindings(root, class_name)
        updated_service_bindings = self._update_service_bindings(root, class_name)
        updated_route_registrations = self._update_route_registrations(root, context)

        self._print_final_report(
            deleted_files=deleted_files,
            updated_bindings=[
                item
                for item in [
                    updated_repository_bindings,
                    updated_service_bindings,
                ]
                if item
            ],
            updated_route_registrations=updated_route_registrations,
            updated_model_exports=updated_model_exports,
            warnings=warnings,
        )

    def _feature_files(self, root: Path, context: dict[str, str]) -> list[Path]:
        class_name = context["class_name"]
        snake_name = context["snake_name"]
        return [
            root / "Controllers" / f"{class_name}Controller.py",
            root / "DTO" / f"{class_name}DTO.py",
            root / "model" / f"{class_name}.py",
            root / "Repositories" / "Contracts" / f"{class_name}Repository.py",
            root / "Repositories" / f"{class_name}RepositoryImpl.py",
            root / "Services" / "Contracts" / f"{class_name}Service.py",
            root / "Services" / f"{class_name}ServiceImpl.py",
        ]

    def _print_confirmation_summary(self, class_name: str, files: list[Path]) -> None:
        self.stdout.write(f"Feature: {class_name}\n")
        self.stdout.write("Files to delete:")
        for path in files:
            self.stdout.write(f"* {path.name}")
        self.stdout.write("\nBindings to remove:")
        self.stdout.write(f"* {class_name}Repository -> {class_name}RepositoryImpl")
        self.stdout.write(f"* {class_name}Service -> {class_name}ServiceImpl")
        self.stdout.write("")

    def _confirmed(self) -> bool:
        answer = input("Continue? [y/N]: ").strip().lower()
        return answer in {"y", "yes"}

    def _delete_files(self, files: list[Path]) -> tuple[list[Path], list[str]]:
        deleted_files = []
        warnings = []

        for path in files:
            if not path.exists():
                warnings.append(f"Missing file skipped: {path}")
                continue
            path.unlink()
            deleted_files.append(path)

        return deleted_files, warnings

    def _update_model_exports(self, root: Path, class_name: str) -> bool:
        path = root / "model" / "__init__.py"
        if not path.exists():
            return False

        original = path.read_text(encoding="utf-8")
        content = self._remove_lines_containing(
            original,
            [
                f"from .{class_name} import {class_name}",
                f"from app.model.{class_name} import {class_name}",
            ],
        )
        exports = [
            value
            for value in self._extract_all_values(content)
            if value != class_name
        ]
        content = self._replace_or_append_all(content, exports)
        path.write_text(content, encoding="utf-8")
        return content != original

    def _update_repository_bindings(self, root: Path, class_name: str) -> str | None:
        path = root / "config" / "binding" / "repositories.py"
        if not path.exists():
            return None

        original = path.read_text(encoding="utf-8")
        content = self._remove_lines_containing(
            original,
            [
                f"{class_name}Repository",
                f"{class_name}RepositoryImpl",
            ],
        )
        path.write_text(content, encoding="utf-8")
        if content == original:
            return None
        return f"{class_name}Repository -> {class_name}RepositoryImpl"

    def _update_service_bindings(self, root: Path, class_name: str) -> str | None:
        path = root / "config" / "binding" / "services.py"
        if not path.exists():
            return None

        original = path.read_text(encoding="utf-8")
        content = self._remove_service_binding_block(original, class_name)
        path.write_text(content, encoding="utf-8")
        if content == original:
            return None
        return f"{class_name}Service -> {class_name}ServiceImpl"

    def _update_route_registrations(self, root: Path, context: dict[str, str]) -> bool:
        updated_user_routes = self._update_user_v1_routes(root, context)
        updated_core_routes = self._update_legacy_core_route_registration(root, context)
        return updated_user_routes or updated_core_routes

    def _update_user_v1_routes(self, root: Path, context: dict[str, str]) -> bool:
        class_name = context["class_name"]
        path = root / "Routes" / "user" / "v1.py"
        if not path.exists():
            return False

        original = path.read_text(encoding="utf-8")
        content = self._remove_lines_containing(
            original,
            [f"from app.Controllers.{class_name}Controller import {class_name}Controller"],
        )
        content = self._remove_marked_route_block(content, class_name)
        path.write_text(content, encoding="utf-8")
        return content != original

    def _update_legacy_core_route_registration(self, root: Path, context: dict[str, str]) -> bool:
        core_urls_path = root.parent / "core" / "urls.py"
        if not core_urls_path.exists():
            return False

        original = core_urls_path.read_text(encoding="utf-8")
        route_module = f"app.Routes.{context['snake_name']}_routes"
        content = self._remove_lines_containing(original, [route_module])
        core_urls_path.write_text(content, encoding="utf-8")
        return content != original

    def _remove_marked_route_block(self, content: str, class_name: str) -> str:
        pattern = (
            rf"\n?\s*# {re.escape(class_name)} routes\n"
            rf"(?:.*\n)*?"
            rf"\s*# End {re.escape(class_name)} routes\n?"
        )
        return re.sub(pattern, "\n", content, flags=re.MULTILINE).rstrip() + "\n"

    def _remove_service_binding_block(self, content: str, class_name: str) -> str:
        lines = content.splitlines()
        cleaned = []
        index = 0

        while index < len(lines):
            line = lines[index]
            if any(
                token in line
                for token in [
                    f"{class_name}Repository",
                    f"{class_name}Service",
                    f"{class_name}ServiceImpl",
                ]
            ):
                index += 1
                continue

            if line.strip() == "container.register(" and index + 2 < len(lines):
                block = "\n".join(lines[index : index + 4])
                if f"{class_name}Service" in block or f"{class_name}ServiceImpl" in block:
                    index += 4
                    continue

            cleaned.append(line)
            index += 1

        return "\n".join(cleaned).rstrip() + "\n"

    def _remove_lines_containing(self, content: str, needles: list[str]) -> str:
        lines = [
            line
            for line in content.splitlines()
            if not any(needle in line for needle in needles)
        ]
        return "\n".join(lines).rstrip() + "\n"

    def _extract_all_values(self, content: str) -> list[str]:
        match = re.search(r"__all__\s*=\s*\[(.*?)\]", content, re.DOTALL)
        if not match:
            return []
        return re.findall(r"[\"']([^\"']+)[\"']", match.group(1))

    def _replace_or_append_all(self, content: str, exports: list[str]) -> str:
        exports = sorted(dict.fromkeys(exports))
        all_block = "__all__ = [\n" + "".join(f'    "{value}",\n' for value in exports) + "]"
        if re.search(r"__all__\s*=\s*\[.*?\]", content, re.DOTALL):
            return re.sub(r"__all__\s*=\s*\[.*?\]", all_block, content, flags=re.DOTALL)
        return f"{content.rstrip()}\n{all_block}\n"

    def _print_final_report(
        self,
        deleted_files: list[Path],
        updated_bindings: list[str],
        updated_route_registrations: bool,
        updated_model_exports: bool,
        warnings: list[str],
    ) -> None:
        self.stdout.write(self.style.SUCCESS("\nRemove feature complete."))

        self.stdout.write("\nDeleted files:")
        if deleted_files:
            for path in deleted_files:
                self.stdout.write(f"* {path}")
        else:
            self.stdout.write("* None")

        self.stdout.write("\nUpdated bindings:")
        if updated_bindings:
            for binding in updated_bindings:
                self.stdout.write(f"* {binding}")
        else:
            self.stdout.write("* None")

        self.stdout.write("\nUpdated route registrations:")
        self.stdout.write("* Yes" if updated_route_registrations else "* No")

        self.stdout.write("\nUpdated model exports:")
        self.stdout.write("* Yes" if updated_model_exports else "* No")

        self.stdout.write("\nWarnings:")
        if warnings:
            for warning in warnings:
                self.stdout.write(self.style.WARNING(f"* {warning}"))
        else:
            self.stdout.write("* None")

    def _normalize_class_name(self, raw_name: str) -> str:
        cleaned = re.sub(r"[^0-9a-zA-Z_]", "", raw_name.strip())
        return "".join(part[:1].upper() + part[1:] for part in re.split(r"[_\s]+", cleaned) if part)

    def _to_snake_case(self, value: str) -> str:
        return re.sub(r"(?<!^)(?=[A-Z])", "_", value).lower()

